vendors:
  cisco_ios:
    commands:
      version: show version
      interfaces: show ip interface brief
      inventory: show inventory
    timeout: 30
    delay_factor: 1
    
  cisco_xe:
    commands:
      version: show version
      interfaces: show ip interface brief
      inventory: show inventory
      platform: show platform
    timeout: 30
    delay_factor: 1